# Generated by Django 4.2.2 on 2023-07-09 08:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.TextField()),
                ('not_present', models.TextField()),
                ('audience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('score', models.CharField(max_length=255)),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('convocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season_manager.convocation')),
            ],
        ),
    ]
