# Generated by Django 4.2.2 on 2023-07-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.CharField(default='10:00', max_length=255),
        ),
    ]
