# Generated by Django 4.2.2 on 2023-07-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0002_match_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocation',
            name='audience',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='convocation',
            name='not_present',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='convocation',
            name='present',
            field=models.JSONField(),
        ),
    ]
