# Generated by Django 4.2.2 on 2023-07-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0003_alter_convocation_audience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='date',
            new_name='match_date',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='link',
            new_name='match_link',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='place',
            new_name='match_place',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score',
            new_name='match_score',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='status',
            new_name='match_status',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='time',
            new_name='match_time',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='title',
            new_name='match_title',
        ),
    ]
