# Generated by Django 4.2.2 on 2023-07-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0004_rename_date_match_match_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convocation',
            old_name='not_present',
            new_name='absent',
        ),
    ]
