# Generated by Django 4.2.2 on 2023-07-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0005_rename_not_present_convocation_absent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_place',
            new_name='match_place_link',
        ),
    ]
