# Generated by Django 4.2.2 on 2023-07-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0006_rename_match_place_match_match_place_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_link',
        ),
        migrations.AddField(
            model_name='match',
            name='match_place',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_place_link',
            field=models.TextField(default='None'),
        ),
    ]
