# Generated by Django 4.2.2 on 2023-07-09 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0007_remove_match_match_link_match_match_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=255)),
                ('game_date', models.DateField(default=datetime.date.today)),
                ('game_time', models.CharField(default='10:00', max_length=255)),
                ('game_score', models.CharField(max_length=255)),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('game_status', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('game_place', models.CharField(default='None', max_length=255)),
                ('game_place_link', models.TextField(default='None')),
                ('convocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season_manager.convocation')),
            ],
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
