# Generated by Django 4.2.2 on 2023-07-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0008_game_delete_match'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Convocation',
            new_name='Poll',
        ),
    ]
