# Generated by Django 4.2.2 on 2023-07-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0010_rename_convocation_game_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_assists',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='game',
            name='game_goals',
            field=models.JSONField(default=[]),
        ),
    ]
