# Generated by Django 4.2.2 on 2023-07-09 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0011_game_game_assists_game_game_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_assists',
            new_name='game_goals_assists',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_goals',
        ),
    ]
