# Generated by Django 4.2.2 on 2023-07-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0012_rename_game_assists_game_game_goals_assists_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_goals_assists',
            new_name='game_assists',
        ),
        migrations.AddField(
            model_name='game',
            name='game_goals',
            field=models.JSONField(default=[]),
        ),
    ]
