# Generated by Django 4.2.2 on 2023-07-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0016_alter_poll_absent_alter_poll_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_season',
            field=models.CharField(default='', max_length=255),
        ),
    ]
