# Generated by Django 4.2.2 on 2023-07-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0017_game_game_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_place_link',
        ),
        migrations.AddField(
            model_name='game',
            name='game_coordinates',
            field=models.JSONField(default=[]),
        ),
    ]
