# Generated by Django 4.2.2 on 2023-07-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0018_remove_game_game_place_link_game_game_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_season',
            field=models.CharField(default='', max_length=255),
        ),
    ]
