# Generated by Django 4.2.2 on 2023-07-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0019_poll_poll_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_assists',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_coordinates',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_goals',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_redcards',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_yellowcards',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='absent',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='audience',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='present',
            field=models.TextField(default='[]'),
        ),
    ]
