# Generated by Django 4.2.2 on 2023-07-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0021_alter_game_game_assists_alter_game_game_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_team_away',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='game_team_home',
            field=models.CharField(default='', max_length=255),
        ),
    ]
