# Generated by Django 4.2.3 on 2023-07-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0022_game_game_team_away_game_game_team_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_coordinates',
        ),
    ]
