# Generated by Django 4.2.3 on 2023-08-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0024_ground_game_game_ground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_ground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season_manager.ground'),
        ),
    ]
