# Generated by Django 4.2.3 on 2023-08-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0025_alter_game_game_ground'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_place',
        ),
    ]
