# Generated by Django 4.2.3 on 2023-08-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0029_player_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.CharField(choices=[('Planned', 'planned'), ('Delayed', 'delayed'), ('Played', 'played')], default='planned', max_length=255),
        ),
    ]
