# Generated by Django 4.2.3 on 2023-09-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0031_alter_game_game_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('amical', 'Amical'), ('championnat', 'Championnat'), ('coupe', 'Championnat')], default='championnat', max_length=255),
        ),
    ]
