# Generated by Django 4.2.3 on 2023-09-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0032_config_alter_game_game_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
