# Generated by Django 4.2.3 on 2023-10-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0033_delete_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('team_status', models.BooleanField()),
                ('team_logo', models.ImageField(upload_to='teams')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('amical', 'Amical'), ('championnat', 'Championnat'), ('coupe', 'Coupe')], default='championnat', max_length=255),
        ),
    ]
