# Generated by Django 4.2.3 on 2023-10-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0034_team_alter_game_game_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_status',
            new_name='status',
        ),
    ]
