# Generated by Django 4.2.3 on 2023-10-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0035_rename_team_logo_team_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(upload_to='public/assets/teams'),
        ),
    ]
