# Generated by Django 4.2.3 on 2023-10-02 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0036_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_team_home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='season_manager.team'),
        ),
    ]
