# Generated by Django 4.2.3 on 2023-10-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0037_alter_game_game_team_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_team_home',
            field=models.CharField(default='', max_length=255),
        ),
    ]
