# Generated by Django 4.2.3 on 2023-10-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season_manager', '0038_alter_game_game_team_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_team_away',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away', to='season_manager.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_team_home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='season_manager.team'),
        ),
    ]
